### PR TITLE
try to automatically grab 16.04 binaries on 16.04

### LINKED ISSUE #7: Provider BinDeps.BuildProcess failed to satisfy dependency ddApp
I got this error when running `Pkg.build("DrakeVisualizer")`

```
INFO: Building PyCall
Fetching package metadata .......
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /home/blegat/.julia/v0.5/Conda/deps/usr:
#
numpy                     1.11.2                   py27_0  
INFO: PyCall is using /home/blegat/.julia/v0.5/Conda/deps/usr/bin/python (Python 2.7.11) at /home/blegat/.julia/v0.5/Conda/deps/usr/bin/python, libpython = /home/blegat/.julia/v0.5/Conda/deps/usr/lib/libpython2.7
INFO: Building PyLCM
WARNING: `@linux` is deprecated, use `@static is_linux()` instead
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in @linux(::Any, ::Any) at ./deprecated.jl:484
 in include_from_node1(::String) at ./loading.jl:488
 in evalfile(::String, ::Array{String,1}) at ./loading.jl:504 (repeats 2 times)
 in cd(::##2#4, ::String) at ./file.jl:59
 in (::##1#3)(::IOStream) at ./none:13
 in open(::##1#3, ::String, ::String) at ./iostream.jl:113
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /home/blegat/.julia/v0.5/PyLCM/deps/build.jl, in expression starting on line 17
-I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7
-I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7
-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
INFO: Building DrakeVisualizer
INFO: Attempting to Create directory /home/blegat/.julia/v0.5/DrakeVisualizer/deps/downloads
INFO: Downloading file http://people.csail.mit.edu/patmarion/software/director/releases/director-0.1.0-linux.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9094k  100 9094k    0     0  1557k      0  0:00:05  0:00:05 --:--:-- 1518k
INFO: Done downloading file http://people.csail.mit.edu/patmarion/software/director/releases/director-0.1.0-linux.tar.gz
INFO: Attempting to Create directory /home/blegat/.julia/v0.5/DrakeVisualizer/deps/usr
==========================================================[ ERROR: DrakeVisualizer ]===========================================================

LoadError: Provider BinDeps.BuildProcess failed to satisfy dependency ddApp
while loading /home/blegat/.julia/v0.5/DrakeVisualizer/deps/build.jl, in expression starting on line 46

===============================================================================================================================================

===============================================================[ BUILD ERRORS ]================================================================

WARNING: DrakeVisualizer had build errors.

 - packages with build errors remain installed in /home/blegat/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("DrakeVisualizer")`
 - build a single package by running its `deps/build.jl` script

===============================================================================================================================================
```

I have written a little C file to see what is the error returned by dlopen and I get

```
could not open file [libddApp.so]: libQVTK.so.5.8: cannot open shared object file: No such file or directory
```

As it was suggested in the README, I had done

```
sudo apt-get install libvtk5-qt4-dev python-vtk
```

but it had installed

```
$ ldconfig -p | grep libQVTK                                               
    libQVTK.so.5.10 (libc6,x86-64) => /usr/lib/libQVTK.so.5.10
    libQVTK.so (libc6,x86-64) => /usr/lib/libQVTK.so
```

so I guess that the precompiled binaries are pointing to the wrong version of `libQVTK` :(

### PR DESCRIPTION
**Pull request by rdeits**
fixes #7

### CODE REVIEW

**Comment by blegat** [comment]
I works for me, Thanks a lot !

File: deps/build.jl [hunk 1]
```diff
@@ -15,6 +15,15 @@ director_version = v"0.1.0"
         director = library_dependency("ddApp", aliases=["libddApp"], depends=[python_vtk, python])
     ]
 
+    linux_distributor = strip(readstring(`lsb_release -i -s`))
+    linux_version = VersionNumber(strip(readstring(`lsb_release -r -s`)))
+    if linux_distributor == "Ubuntu" && linux_version >= v"16.04"
+        director_variant = "ubuntu16"
+    else
+        director_variant = "linux"
```
Comment (patmarion) [inline deps/build.jl:23]: @rdeits i'll probably add ubuntu14 to the other package name, too.  I'll update you when that happens.  Thanks for being an early consumer of the binaries!

Comment (rdeits) [reply deps/build.jl:23]: ok, sounds good 😄
